title: Essays and Meditations
description: Personal essays in Persian and English
baseurl: "/essays-and-meditations"
markdown: kramdown

exclude:
  - README.md

collections:
  essays_en:
    output: true
    permalink: /en/:name/
  essays_fa:
    output: true
    permalink: /fa/:name/
